import type { Metadata } from "next";
import { SanityLive } from "@/sanity/lib/live";
import { SidebarProvider } from "@/components/providers/sidebar-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <SidebarProvider>
        <div className="h-full">{children}</div>
      </SidebarProvider>

      <SanityLive />
    </>
  );
}
